% Author: Eduardo Peixoto
% E-mail: eduardopeixoto@ieee.org
function cabac = getCABAC()

cabac = struct('BACParams',[],...
               'BACEngine',[],...
               'BACEngineDecoder',[],...
               'BACContexts_2D',[]);